monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/dev.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event"]
